version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: password
      POSTGRES_DB: your_database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
